"""Alembic environment configuration."""

import os
import sys
from logging.config import fileConfig
from sqlalchemy import engine_from_config
from sqlalchemy import pool
from alembic import context
import sqlalchemy as sa
from sqlalchemy import text
from app.utils.logger import log

# Ensure project root (parent of alembic/) is on sys.path so 'app' package resolves
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
PARENT_DIR = os.path.abspath(os.path.dirname(ROOT_DIR))
if PARENT_DIR not in sys.path:
    sys.path.insert(0, PARENT_DIR)
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

from app.config import settings
from app.models.database import Base

# this is the Alembic Config object
config = context.config

# Interpret the config file for Python logging
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Set sqlalchemy.url from settings
config.set_main_option("sqlalchemy.url", settings.database_url)

# Import all models to ensure they are recognized by Alembic
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        # Ensure expected schema changes from legacy/autogenerated migrations
        # are applied if they are missing. This embeds the logic from the
        # previous standalone revision scripts so environments that don't
        # have the versions files can still ensure the DB schema is correct.
        def _ensure_schema(conn):
            inspector = sa.inspect(conn)
            tables = inspector.get_table_names()

            # messages table: add columns and unique index for platform_message_id
            if 'messages' in tables:
                cols = [c['name'] for c in inspector.get_columns('messages')]
                try:
                    if 'platform_message_id' not in cols:
                        conn.execute(text("ALTER TABLE messages ADD COLUMN platform_message_id VARCHAR"))
                    if 'direction' not in cols:
                        conn.execute(text("ALTER TABLE messages ADD COLUMN direction VARCHAR"))
                    if 'status' not in cols:
                        conn.execute(text("ALTER TABLE messages ADD COLUMN status VARCHAR"))

                    # create unique index if not exists
                    existing_indexes = [idx['name'] for idx in inspector.get_indexes('messages')]
                    if 'ix_messages_platform_message_id' not in existing_indexes:
                        # Some DBs (Postgres) support IF NOT EXISTS for index; use safe create
                        conn.execute(text("CREATE UNIQUE INDEX IF NOT EXISTS ix_messages_platform_message_id ON messages(platform_message_id)"))
                except Exception as e:
                    log.warning(f"Could not apply embedded messages schema changes: {e}")

            # conversations table: add priority and assigned_to
            if 'conversations' in tables:
                cols = [c['name'] for c in inspector.get_columns('conversations')]
                try:
                    if 'priority' not in cols:
                        # set default 'normal'
                        conn.execute(text("ALTER TABLE conversations ADD COLUMN priority VARCHAR DEFAULT 'normal'"))
                    if 'assigned_to' not in cols:
                        conn.execute(text("ALTER TABLE conversations ADD COLUMN assigned_to INTEGER"))
                except Exception as e:
                    log.warning(f"Could not apply embedded conversations schema changes: {e}")

        try:
            _ensure_schema(connection)
        except Exception as e:
            log.warning(f"Schema ensure step failed: {e}")

        context.configure(
            connection=connection,
            target_metadata=target_metadata
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
